<section class="daily-info-section py-4 bg-light">
    <div class="container">
        <div class="row g-4">
            
            {{-- ========================================== --}}
            {{-- Left Side: Prayer Times --}}
            {{-- ========================================== --}}
            <div class="col-lg-6">
                <div class="daily-card h-100 shadow-sm bg-white rounded-3 overflow-hidden border-top-namaz">
                    
                    {{-- Header --}}
                    <div class="card-header bg-white border-bottom p-3 d-flex justify-content-between align-items-center">
                        <h5 class="m-0 fw-bold text-success">
                            <i class="fas fa-mosque me-2"></i>Prayer Times
                        </h5>
                        <small class="text-muted fw-bold bg-light px-2 py-1 rounded" id="hijriDateDisplay">
                            <i class="fas fa-spinner fa-spin"></i>
                        </small>
                    </div>

                    {{-- Body --}}
                    <div class="card-body p-3">
                        <div id="namaz-loader" class="text-center py-4">
                            <div class="spinner-border text-success" role="status"></div>
                        </div>
                        
                        <div class="row g-2 d-none" id="namaz-content">
                            {{-- List generated by JavaScript --}}
                        </div>
                    </div>
                </div>
            </div>

            {{-- ========================================== --}}
            {{-- Right Side: Weather News --}}
            {{-- ========================================== --}}
            <div class="col-lg-6">
                <div class="daily-card h-100 shadow-sm bg-white rounded-3 overflow-hidden border-top-weather">
                    
                    {{-- Header --}}
                    <div class="card-header bg-white border-bottom p-3 d-flex justify-content-between align-items-center">
                        <h5 class="m-0 fw-bold text-warning-dark">
                            <i class="fas fa-cloud-sun-rain me-2"></i>Weather (Dhaka)
                        </h5>
                        <span class="badge bg-warning text-dark"><i class="fas fa-circle text-danger me-1 small"></i>Live</span>
                    </div>

                    {{-- Body --}}
                    <div class="card-body p-3 d-flex align-items-center justify-content-center">
                        
                        <div id="weather-loader" class="text-center py-4">
                            <div class="spinner-border text-warning" role="status"></div>
                        </div>

                        <div id="weather-content" class="w-100 d-none">
                            <div class="row align-items-center">
                                
                                {{-- Left: Big Temperature --}}
                                <div class="col-5 text-center border-end">
                                    <img id="weather-icon" src="https://cdn-icons-png.flaticon.com/512/869/869869.png" alt="Sun" width="60" class="mb-2">
                                    <h2 class="display-4 fw-bold mb-0 text-dark" id="current-temp">--°</h2>
                                    <p class="mb-0 text-muted fw-bold small" id="weather-desc">--</p>
                                </div>

                                {{-- Right: Details --}}
                                <div class="col-7">
                                    <div class="row g-2">
                                        <div class="col-12">
                                            <div class="p-2 bg-light rounded d-flex align-items-center">
                                                <i class="fas fa-temperature-high text-danger me-3 fs-5"></i>
                                                <div>
                                                    <small class="text-muted d-block" style="line-height:1;">Feels Like</small>
                                                    <span class="fw-bold" id="feels-like">--</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="p-2 bg-light rounded d-flex align-items-center">
                                                <i class="fas fa-tint text-primary me-3 fs-5"></i>
                                                <div>
                                                    <small class="text-muted d-block" style="line-height:1;">Humidity</small>
                                                    <span class="fw-bold" id="humidity">--</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="p-2 bg-light rounded d-flex align-items-center">
                                                <i class="fas fa-wind text-secondary me-3 fs-5"></i>
                                                <div>
                                                    <small class="text-muted d-block" style="line-height:1;">Wind Speed</small>
                                                    <span class="fw-bold" id="wind-speed">--</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<style>
    /* Custom Design */
    .daily-card { transition: transform 0.3s ease; }
    .daily-card:hover { transform: translateY(-3px); }
    
    .border-top-namaz { border-top: 4px solid #198754; }
    .border-top-weather { border-top: 4px solid #ffc107; }
    
    .text-warning-dark { color: #d39e00; }

    /* Prayer Time List Design */
    .waqt-item {
        background-color: #f8f9fa;
        border-radius: 6px;
        padding: 8px 10px;
        transition: 0.2s;
        border: 1px solid #eee;
    }
    .waqt-item:hover {
        background-color: #e9ecef;
        border-color: #198754;
    }
    .waqt-name { font-size: 14px; color: #555; }
    .waqt-time { font-size: 16px; color: #000; }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        fetchDailyData();
    });

    function fetchDailyData() {
        // 1. Prayer Time API
        fetch("https://api.aladhan.com/v1/timingsByCity?city=Dhaka&country=Bangladesh&method=1&school=1")
            .then(res => res.json())
            .then(data => {
                if(data.code === 200) renderNamaz(data.data);
            });

        // 2. Weather API
        fetch("https://api.open-meteo.com/v1/forecast?latitude=23.8103&longitude=90.4125&current=temperature_2m,relative_humidity_2m,apparent_temperature,is_day,weather_code,wind_speed_10m&timezone=auto")
            .then(res => res.json())
            .then(data => renderWeather(data.current));
    }

    // --- Render Function: Namaz ---
    function renderNamaz(data) {
        const timings = data.timings;
        const hijri = data.date.hijri;
        document.getElementById('hijriDateDisplay').innerText = `${toBanglaNum(hijri.day)} ${hijri.month.en} ${toBanglaNum(hijri.year)} Hijri`;

        const waqts = [
            { k: 'Fajr', n: 'Fajr', i: 'fa-cloud-sun' },
            { k: 'Sunrise', n: 'Sunrise', i: 'fa-sun', sun: true },
            { k: 'Dhuhr', n: 'Dhuhr', i: 'fa-sun' },
            { k: 'Asr', n: 'Asr', i: 'fa-cloud-sun' },
            { k: 'Maghrib', n: 'Maghrib', i: 'fa-moon' },
            { k: 'Isha', n: 'Isha', i: 'fa-cloud-moon' }
        ];

        let html = '';
        waqts.forEach(w => {
            let time = formatTime(timings[w.k]);
            let iconColor = w.sun ? 'text-warning' : 'text-success';
            html += `
                <div class="col-4 col-md-4">
                    <div class="waqt-item text-center">
                        <i class="fas ${w.i} ${iconColor} mb-1"></i>
                        <div class="waqt-name fw-bold">${w.n}</div>
                        <div class="waqt-time fw-bold">${time}</div>
                    </div>
                </div>
            `;
        });

        document.getElementById('namaz-loader').classList.add('d-none');
        const container = document.getElementById('namaz-content');
        container.classList.remove('d-none');
        container.innerHTML = html;
    }

    // --- Render Function: Weather ---
    function renderWeather(current) {
        document.getElementById('current-temp').innerText = toBanglaNum(Math.round(current.temperature_2m)) + '°C';
        document.getElementById('feels-like').innerText = toBanglaNum(Math.round(current.apparent_temperature)) + '°C';
        document.getElementById('humidity').innerText = toBanglaNum(current.relative_humidity_2m) + '%';
        document.getElementById('wind-speed').innerText = toBanglaNum(current.wind_speed_10m) + ' km/h';
        document.getElementById('weather-desc').innerText = getWeatherCode(current.weather_code);

        // Set Icon (Day/Night and Code)
        let iconSrc = current.is_day ? "https://cdn-icons-png.flaticon.com/512/869/869869.png" : "https://cdn-icons-png.flaticon.com/512/581/581601.png";
        if(current.weather_code > 50) iconSrc = "https://cdn-icons-png.flaticon.com/512/1146/1146858.png"; // Rain
        document.getElementById('weather-icon').src = iconSrc;

        document.getElementById('weather-loader').classList.add('d-none');
        document.getElementById('weather-content').classList.remove('d-none');
    }

    // --- Helper Functions ---
    function formatTime(time24) {
        let [h, m] = time24.split(':');
        h = parseInt(h);
        let ampm = h >= 12 ? '' : ''; // Leaving am/pm out for space, or add if needed
        h = h % 12 || 12;
        return toBanglaNum(`${h}:${m}`);
    }

    // Modified to return English numbers directly
    function toBanglaNum(str) {
        return str; 
    }

    function getWeatherCode(code) {
        if(code === 0) return 'Clear Sky';
        if(code >= 1 && code <= 3) return 'Partly Cloudy';
        if(code >= 45 && code <= 48) return 'Foggy';
        if(code >= 51 && code <= 67) return 'Rainy';
        if(code >= 80 && code <= 99) return 'Thunderstorm';
        return 'Normal';
    }
</script>